name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install flake8
        run: pip install flake8
      - name: Lint code
        run: flake8 .

  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: python -m unittest discover tests/unit || exit 1

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run integration tests
        run: python -m unittest discover tests/integration || exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Deploying to correct environment
        run: |
          echo "Deploying to ${{ github.ref }}"
          BRANCH="${GITHUB_REF##*/}"
          if [[ "$BRANCH" == "dev" ]]; then
            echo "Deploying to DEV..."
          elif [[ "$BRANCH" == "staging" ]]; then
            echo "Deploying to STAGING..."
          elif [[ "$BRANCH" == "main" ]]; then
            echo "Deploying to PRODUCTION..."
          fi

  notify-on-failure:
    if: failure()
    needs: [lint, unit-test, integration-test, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="🚨 GitHub CI/CD pipeline failed for branch *${{ github.ref_name }}* in repo *${{ github.repository }}*. Check Actions tab for details."
